### PR TITLE
Update docs for 3.4

### PR DESCRIPTION
**Pull request by nickw1**
Have significantly updated the docs for location-based so that they are current as at AR.js 3.4, see issue #19.

Also included are revised tutorials for location-based AR.js, both A-Frame and three.js.

@kalwalt @nicolocarpignoli could one of you review the changes, and then if acceptable I will merge. Thanks.

### CODE REVIEW

**Comment by kalwalt** [comment]
I will review this when i have a bit of time, thank you for the PR!

**Comment by nicolocarpignoli** [comment]
wow this is great @nickw1 ! It is all good to me! 

Also, another thing: are there some of my Medium article about location based that are probably outdated/not working anymore? I will edit them in case.

**Review by nicolocarpignoli — APPROVED** [review]

**Comment by nickw1** [comment]
@nicolocarpignoli thanks!

With your tutorial, I think it's just the AR.js location that needs to be updated, isn't this referring to an old version?

`https://raw.githack.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js`

Then I think it will all work fine, so would be great if you could update it! Thanks.

**Comment by kalwalt** [comment]
Great @nickw1 , hadn't the time to look at the full changes but definetely it's a super description! Thank you again for this. 🙂

**Comment by nickw1** [comment]
@kalwalt no worries - @nicolocarpignoli approved so I merged, hope that's ok.

**Pull request merged**
